name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [1.0.11]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v2
      - run: terraform init -get -backend=false -input=false
      - run: terraform fmt -recursive -check=true -write=false